apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app.k8s.io/name: mysql
stringData:
  MYSQL_ROOT_PASSWORD: wppass
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wpuser
  MYSQL_PASSWORD: wppass
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.k8s.io/name: mysql
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.k8s.io/name: mysql
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app.k8s.io/name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.k8s.io/name: mysql
  serviceName: mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
        labels:
          app.k8s.io/name: mysql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  template:
    metadata:
      labels:
        app.k8s.io/name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          envFrom:
            - secretRef:
                name: mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 3
            tcpSocket: 
              port: 3306
      volumes: 
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data     
