apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app.k8s.io/name: phpmyadmin
spec:
  type: ClusterIP
  selector:
    app.k8s.io/name: phpmyadmin
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app.k8s.io/name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.k8s.io/name: phpmyadmin
  template:
    metadata:
      labels:
        app.k8s.io/name: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:5
          env:
            - name: PMA_HOST
              value: mysql
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin
  labels:
    app.k8s.io/name: phpmyadmin
spec:
  rules:
    - host: phpmyadmin.dwsclass.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin
                port:
                  number: 80
