apiVersion: v1
kind: Service
metadata:
  name: poste
  labels:
    app.k8s.io/name: poste
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.k8s.io/name: poste
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
---
apiVersion: v1
kind: Service
metadata:
  name: mailserver
  labels:
    app.k8s.io/name: poste
spec:
  type: LoadBalancer
  selector:
    app.k8s.io/name: poste
  ports:
    - port: 25
      name: smtp
    - port: 110
      name: pop3
    - port: 143
      name: imap
    - port: 465
      name: smtps
    - port: 587
      name: msa
    - port: 993
      name: imaps
    - port: 995
      name: pop3s
    - port: 4190
      name: sieve
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: poste
  labels:
    app.k8s.io/name: poste
spec:
  replicas: 1
  selector:
    matchLabels:
      app.k8s.io/name: poste
  serviceName: poste
  volumeClaimTemplates:
    - metadata:
        name: poste-data
        labels:
          app.k8s.io/name: poste
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  template:
    metadata:
      labels:
        app.k8s.io/name: poste
    spec:
      containers:
        - name: poste
          image: analogic/poste.io:2
          env:
            - name: TZ
              value: Asia/Tehran
            - name: HTTPS
              value: "OFF"
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 25
            - containerPort: 110
            - containerPort: 143
            - containerPort: 465
            - containerPort: 587
            - containerPort: 993
            - containerPort: 995
            - containerPort: 4190
          volumeMounts:
            - name: poste-data
              mountPath: /data
      volumes: 
        - name: poste-data
          persistentVolumeClaim:
            claimName: poste-data
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poste
  labels:
    app.k8s.io/name: poste
spec:
  rules:
    - host: mail.dwsclass.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: poste
                port:
                  number: 80

