apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app.k8s.io/name: wordpress
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.k8s.io/name: wordpress
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
  labels:
    app.k8s.io/name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app.k8s.io/name: wordpress
  serviceName: wordpress
  volumeClaimTemplates:
    - metadata:
        name: wordpress-data
        labels:
          app.k8s.io/name: wordpress
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  template:
    metadata:
      labels:
        app.k8s.io/name: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:5
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
      volumes: 
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-data    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  labels:
    app.k8s.io/name: wordpress
spec:
  rules:
    - host: dwsclass.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
